# -*- mode: ruby -*-
# vi: set ft=ruby :
# This script to install Kubernetes will get executed after we have provisioned the box
$configurations = <<-SCRIPT
set -e
#Letting iptables see bridged traffic
cat <<EOF | sudo tee /etc/modules-load.d/k8s.conf
br_netfilter
EOF

cat <<EOF | sudo tee /etc/sysctl.d/k8s.conf
net.bridge.bridge-nf-call-ip6tables = 1
net.bridge.bridge-nf-call-iptables = 1
EOF
sudo sysctl --system

# kubelet requires swap off
swapoff -a
# keep swap off after reboot
sudo sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab
# Set up Kubernetes
set -e
#kubeadm config images pull --kubernetes-version=v1.18.0
kubeadm init --apiserver-cert-extra-sans=127.0.0.1 --kubernetes-version=v1.18.0
# Set up admin creds for the vagrant user
echo Copying credentials to /home/vagrant...
sudo mkdir -p /root/.kube
cp -i /etc/kubernetes/admin.conf /root/.kube/config
chown $(id -u vagrant):$(id -g vagrant) /root/.kube/config
cp /etc/kubernetes/admin.conf /vagrant/

kubectl apply -f https://docs.projectcalico.org/archive/v3.19/manifests/calico.yaml 
kubectl taint nodes --all node-role.kubernetes.io/master-

SCRIPT

Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |v|
    v.memory = 4096
    v.cpus = 2
  end
  # Specify your hostname if you like
  config.vm.hostname = "master1"
  config.vm.box = "anisa-cka/ubuntu-base"
  config.vm.network "private_network", type: "dhcp"
  config.vm.network "forwarded_port", guest: 6443, host: 6443
  # Specify the shared folder mounted from the host if you like
  # By default you get "." synced as "/vagrant"
  # config.vm.synced_folder ".", "/folder"
  config.vm.provision "shell", inline: $configurations
end
